// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMaBqxTr5BNCQnxYogZbhP9ANVuvour8',
    appId: '1:584759110771:web:9da19cb32b84ab3be84e06',
    messagingSenderId: '584759110771',
    projectId: 'lmnop-fd3dd',
    authDomain: 'lmnop-fd3dd.firebaseapp.com',
    storageBucket: 'lmnop-fd3dd.appspot.com',
    measurementId: 'G-PE001QFS4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1FaS2JY3hDFmq7uL9f_Ae8NljorvGt4',
    appId: '1:584759110771:android:92b78b134c87ba0ae84e06',
    messagingSenderId: '584759110771',
    projectId: 'lmnop-fd3dd',
    storageBucket: 'lmnop-fd3dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDwk_L2BFcwqGvuNxS5ScbO4-THBBAgVk',
    appId: '1:584759110771:ios:bc379909a31dfee0e84e06',
    messagingSenderId: '584759110771',
    projectId: 'lmnop-fd3dd',
    storageBucket: 'lmnop-fd3dd.appspot.com',
    iosClientId: '584759110771-ao1kas5hq51o2ecm0m1fep83jkh7p3ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmnop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDwk_L2BFcwqGvuNxS5ScbO4-THBBAgVk',
    appId: '1:584759110771:ios:bc379909a31dfee0e84e06',
    messagingSenderId: '584759110771',
    projectId: 'lmnop-fd3dd',
    storageBucket: 'lmnop-fd3dd.appspot.com',
    iosClientId: '584759110771-ao1kas5hq51o2ecm0m1fep83jkh7p3ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmnop',
  );
}
